swagger: "2.0"
info:
  description: ""
  version: "1.0.0"
  title: "Yurkas order"
  contact:
    email: "d.karpilenya@yurkas.by"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localHost"
basePath: "/v1"
tags:
- name: "Order"
  description: "Access orders"
schemes:
- "https"
- "http"
paths:
  /order:
    post:
      tags:
      - "Order"
      summary: "Place an order"
      description: ""
      operationId: "placeOrder"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "order placed"
        required: true
        schema:
          $ref: "#/definitions/Order"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/successful"
        "400":
          description: "Invalid Order"
  /order/{orderId}{counterpartyInn}:
    get:
      tags:
      - "Order"
      summary: "Find purchase order by ID"
      operationId: "getOrderById"
      produces:
      - "application/json"
      parameters:
      - name: "orderId"
        in: "path"
        description: "ID заказа по которому нужно получить статус"
        required: true
        type: "integer"
        format: "int64"
      - name: "counterpartyInn"
        in: "path"
        description: "ИНН контрагента"
        required: true
        type: "string"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/successful"
        "400":
          description: "Bad Request"
        "404":
          description: "Order not found"
definitions:
  Order:
    type: "object"
    properties:
      warehouse:
        type: "string"
        description: "Склад оргранизации"
        enum:
        - "Moscow"
        - "Spb"
      organization:
        type: "string"
        description: "Название оргранизации"
        enum:
        - "Yurkas"
        - "Germes"
        - "YurkasSpb"  
      counterpartyInn:
        type: "string"
        description: "ИНН"
      orderId:
        type: "integer"
        format: "int64"
        description: "Номер входящего сообщения"
      tradePoint:
        type: "string"
        description: "Кординаты торговой точки в формате"
      formOfPayment:
        type: "string"
        description: "Форма расчетов"
        enum:
        - "NAL"
        - "BNAL"
      goods:
        $ref: "#/definitions/goods"
    xml:
      name: "Order"
  successful:
    type: "object"
    properties:
      status:
        type: "string"
        description: "Статус заказа"
        enum:
        - "accepted"
        - "inprogress"
        - "closed"
        - "completed"
    xml:
      name: "successful"
  goods:
    type: "object"
    properties:
      barcode:
        type: "string"
        description: "Штрихкод"
      count:
        type: "integer"
        format: "int64"
    xml:
      name: "goods"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"